AllCops:
  TargetRubyVersion: 2.7

inherit_from:
- .rubocop-relaxed.yml

Metrics/BlockLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Naming/VariableNumber:
  Enabled: false
