AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

inherit_from:
  - .rubocop_todo.yml
  - .rubocop-relaxed.yml

Metrics/BlockLength:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashSyntax:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Naming/VariableNumber:
  Enabled: false
